# Saved ó±„« /.config/starship.toml

# removes the default new line
add_newline = false

[directory]
home_symbol = 'ó±„« '
style = 'cyan'

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]
# success_symbol = '[âœ](bold green)'
success_symbol = '[ó±©](bold purple)'
error_symbol = '[âœ—](bold red)'
vimcmd_symbol = '[V](bold purple)'
# The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

[battery]
full_symbol = 'ğŸ”‹'

[[battery.display]]
threshold = 25
style = 'red'
